# Generated by Django 6.0.6 on 2026-06-18 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_zona', models.CharField(max_length=100)),
                ('tarifa_por_kg', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha_envio', models.DateField()),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='logistica.repartidor')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='logistica.zona')),
            ],
        ),
    ]
